[package]
name = "passthrough-rs"
version = "0.0.0"
publish = false
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]

[build-dependencies]
bindgen = "0.51"
pkg-config = "0.3"
