[package]
name = "passthrough-rs"
version = "0.0.0"
publish = false
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
log = "0.4"
pretty_env_logger = "0.2"

[build-dependencies]
bindgen = "0.51"
pkg-config = "0.3"
