name: Rust

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt-get update -yqq
        apt-get install -yqq --no-install-recommends \
             build-essential \
             pkg-config \
             fuse3 \
             libfuse3-dev \
             udev \
             libudev-dev
    - name: Show tools version
      run: |
        rustc --version
        cargo --version
    - name: Build
      run: cargo build --all --verbose
    - name: Run tests
      run: cargo test --all --verbose

  osx:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install dependencies
      run: |
        brew cask install osxfuse
        brew install pkg-config
    - name: Show tools version
      run: |
        rustc --version
        cargo --version
    - name: Build
      run: cargo build --all --verbose
    - name: Run tests
      run: cargo test --all --verbose
