name: Rust

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt-get update -yqq
        apt-get install -yqq --no-install-recommends \
             build-essential \
             pkg-config \
             llvm-dev \
             libclang-dev \
             clang \
             fuse3 \
             libfuse3-dev \
             udev \
             libudev-dev
    - name: Build
      run: cargo build --all --verbose
    - name: Run tests
      run: cargo test --all --verbose
